name: dbt CI Workflow
on:
  push:
    branches:
      - dev
      - 'feature/**'

permissions:
  contents: read
  actions: read
  
jobs:
  dbt_ci_build:
    runs-on: ubuntu-latest
    env:
      MOTHERDUCK_TOKEN: ${{ secrets.MOTHERDUCK_TOKEN }}

    steps:
      # Step 1: Check out repository code
      - name: Check out repository code
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Step 3: Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install duckdb==1.1.4 dbt-duckdb
    
      # Step 4: Configure dbt Profile
      - name: Configure dbt Profile
        run: |
            mkdir -p ~/.dbt
            cat <<EOF > ~/.dbt/profiles.yml
            portfolio_project_2:
              outputs:
                  dev:
                    type: duckdb
                    path: "md:finance"
                    motherduck_token: "{{ env_var('MOTHERDUCK_TOKEN') }}"
                    schema: analytics_dev
                    threads: 4
              target: dev
            EOF
      #Step 5: Download manifest.json file from the prod environment 
      - name: Download prod manifest from CD workflow
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: cd.yml
          workflow_conclusion: success
          name: prod-state
          path: prod_state
          github_token: ${{ secrets.GITHUB_TOKEN }} 
      
      # Step 6: dbt build
      - name: dbt build
        run: |
          dbt deps
          dbt build \
            --target dev \
            --defer \
            --state prod_state \
            --select "state:modified+"

